### ISSUE TITLE
5-3 코드 실행 오류

### ISSUE THREAD

**Issue by itggangpae** [lovedlim/tensorflow#34]
5-3 코드가 모델을 훈련하려고 하면 에러가 발생하던데요
예전에는 되었던것 같던데 텐서플로 버전 에러 일까요
제가 모든 코드를 실행해보고 수정하는 편인데 작년 가을에는 분명히 잘 수행되었던것 같습니다.
다시 한번 확인 부탁드립니다. 고생이 많으십니다.

**Comment by teddylee777** [comment]
안녕하세요?
코드 실행시 오류가 난 부분에서의 코드, 오류 메시지를 첨부해  주시면 답변드리겠습니다.
감사합니다.

**Comment by itggangpae** [comment]
코드 부분
# 학습조기종료
early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=2)

# 학습
history = model.fit(train_padded, train_labels, 
                validation_data=(valid_padded, valid_labels), 
                callbacks=[early_stop, checkpoint], batch_size=64, epochs=10, verbose=2)

에러 메시지
Epoch 1/10
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/98/j21dd2qs46b69mwc94dgyxnr0000gn/T/ipykernel_24435/2956815114.py in <module>
      3 
      4 # 학습
----> 5 history = model.fit(train_padded, train_labels, 
      6                 validation_data=(valid_padded, valid_labels),
      7                 callbacks=[early_stop, checkpoint], batch_size=64, epochs=10, verbose=2)

~/opt/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

~/opt/anaconda3/lib/python3.9/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 860, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/engine/training.py", line 918, in compute_loss
        return self.compiled_loss(
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/losses.py", line 1932, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/Users/adam/opt/anaconda3/lib/python3.9/site-packages/keras/backend.py", line 5247, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    ValueError: `logits` and `labels` must have the same shape, received ((64, 74, 1) vs (64,)).
